### ISSUE TITLE
Didn't work on AirPortSettings macho-binary

### ISSUE THREAD

**Issue by andrewwiik** [inoahdev/tbd#3]
Didn't work on the following valid mach-o binary that Hopper can see the exported symbols for.
[AirPortSettings.zip](https://github.com/inoahdev/tbd/files/1207022/AirPortSettings.zip)

**Comment by inoahdev** [comment]
AirPortSettings' objective-c classes and ivar symbol are not marked external (most are described as N_PEXT or private-external) which is why nothing was outputted. The latest commit fixes this by allowing objective-c class and ivar symbols (or so we're told) to bypass this check (as this has no effect on runtime). As a side effect of this, all objective-c classes and ivars will now be outputted whether or not they're meant to be internal-only. In the future, I will provide users more options on what symbols are used
